post http://localhost:4000/api/user
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDFhNTNjNmVmMzkwNDE0MjM4OWZmMSIsImlhdCI6MTY5MjA0MDU5OSwiZXhwIjoxNjkyMTI2OTk5fQ.QuStqh0_JqcVlc-ALqD-E4mYufkaGRagzO8WnNaM4fw

{
    "username": "user1",
    "email": "a@1.com",
    "password": "1234",
    "roles": ["user"]
}